### ISSUE TITLE
Add support for play-json 2.9 & 3.0

### ISSUE THREAD

**Issue by tarmath** [sangria-graphql/sangria-play-json#238]
play (and play-json) 2.9.0 and 3.0.0 were released a few weeks back, as can be seen here:

https://github.com/playframework/playframework/releases/tag/2.9.0
https://github.com/playframework/playframework/releases/tag/3.0.0

It would be great if this project could publish a compatible release built on top of it!

**Comment by b-eyselein** [comment]
Sorry to bother, but is there a chance that the new version(s) is going to be published soon?
